# -*- coding: utf-8 -*-
"""DS_Intersnship_Task1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/124IEWNmfm2Z-JCSs-P7ViI3_GfOJatq1
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

df= pd.read_csv("Titanic-Dataset.csv")

print(df.info())

print(df.describe())

print(df.head())

print(df.tail())

df.isnull().sum()

df['Age']=df['Age'].fillna(df['Age'].mean())
df.isnull().sum()

df=pd.get_dummies(df, columns=['Sex', 'Embarked'], drop_first=True)

df.corr()

X = df.drop(['PassengerId', 'Survived', 'Name', 'Ticket', 'Cabin'], axis=1)
y = df['Survived']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Logistic Regression
# Initialize and train the model
logistic_reg = LogisticRegression(max_iter=1000, random_state=42)
logistic_reg.fit(X_train, y_train)
y_pred_logistic = logistic_reg.predict(X_test)
accuracy_logistic = accuracy_score(y_test, y_pred_logistic)
print("Logistic Regression Accuracy:", accuracy_logistic)
print("Classification Report:")
print(classification_report(y_test, y_pred_logistic))

# Random Forest Classifier
rf_classifier = RandomForestClassifier(random_state=42)
rf_classifier.fit(X_train, y_train)
y_pred = rf_classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Random Forest Classifier Accuracy:", accuracy)
print("Classification Report:")
print(classification_report(y_test, y_pred))